spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    username: root
    password: HareKrsna#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#server:
#  servlet:
#    context-path: /api